import { Platform } from 'react-native';

const androidOnly = new Set(['android']);
const iosOnly = new Set(['ios']);
const allPlatforms = new Set(['android', 'ios']);

export const screenList: {
  name: string;
  platforms: Set<String>;
  excludedOnTV?: boolean;
}[] = [
  { name: 'AlertDialogScreen', platforms: androidOnly },
  { name: 'AnimatedVisibilityScreen', platforms: androidOnly },
  { name: 'AnimationModifierScreen', platforms: iosOnly },
  { name: 'BadgeScreen', platforms: androidOnly },
  { name: 'BasicAlertDialogScreen', platforms: androidOnly },
  { name: 'BottomSheetScreen', platforms: iosOnly, excludedOnTV: true },
  { name: 'ButtonScreen', platforms: allPlatforms },
  { name: 'CardScreen', platforms: androidOnly },
  { name: 'CarouselScreen', platforms: allPlatforms, excludedOnTV: true },
  { name: 'ChartScreen', platforms: iosOnly },
  { name: 'CheckboxScreen', platforms: androidOnly },
  { name: 'ChipScreen', platforms: androidOnly },
  { name: 'ColorPickerScreen', platforms: iosOnly, excludedOnTV: true },
  {
    name: 'CommunityBottomSheetScreen',
    platforms: allPlatforms,
    excludedOnTV: true,
  },
  {
    name: 'CommunityDateTimePickerScreen',
    platforms: allPlatforms,
    excludedOnTV: true,
  },
  { name: 'CommunityMaskedViewScreen', platforms: allPlatforms },
  {
    name: 'CommunityPickerScreen',
    platforms: allPlatforms,
    excludedOnTV: true,
  },
  { name: 'CommunitySegmentedControlScreen', platforms: allPlatforms },
  { name: 'ConfirmationDialogScreen', platforms: iosOnly },
  { name: 'ContentTransitionScreen', platforms: iosOnly },
  { name: 'ContextMenuScreen', platforms: iosOnly },
  { name: 'DatePickerScreen', platforms: iosOnly, excludedOnTV: true },
  { name: 'DateTimePickerScreen', platforms: allPlatforms, excludedOnTV: true },
  { name: 'DividerScreen', platforms: androidOnly },
  { name: 'DropdownMenuScreen', platforms: androidOnly },
  { name: 'ExposedDropdownMenuBoxScreen', platforms: androidOnly },
  { name: 'FloatingActionButtonScreen', platforms: androidOnly },
  { name: 'FormScreen', platforms: iosOnly },
  { name: 'GaugeScreen', platforms: iosOnly, excludedOnTV: true },
  { name: 'GlassEffectScreen', platforms: iosOnly },
  { name: 'GraphicsLayerScreen', platforms: androidOnly },
  { name: 'GridScreen', platforms: iosOnly },
  { name: 'HorizontalFloatingToolbarScreen', platforms: androidOnly },
  { name: 'HorizontalPagerScreen', platforms: androidOnly },
  { name: 'HostingRNViewsScreen', platforms: allPlatforms },
  { name: 'IconButtonScreen', platforms: androidOnly },
  { name: 'ImageScreen', platforms: iosOnly },
  { name: 'JetpackComposePrimitivesScreen', platforms: androidOnly },
  { name: 'LazyColumnRowScreen', platforms: androidOnly },
  { name: 'LazyStackScreen', platforms: iosOnly },
  { name: 'LinkScreen', platforms: iosOnly },
  { name: 'ListScreen', platforms: allPlatforms },
  { name: 'MaskScreen', platforms: iosOnly },
  { name: 'MatchedGeometryEffectScreen', platforms: iosOnly },
  { name: 'MaterialColorsScreen', platforms: androidOnly },
  { name: 'MenuScreen', platforms: iosOnly },
  { name: 'ModifiersScreen', platforms: allPlatforms },
  { name: 'OverlayScreen', platforms: iosOnly },
  { name: 'PickerScreen', platforms: iosOnly },
  { name: 'PopoverScreen', platforms: iosOnly },
  { name: 'ProgressScreen', platforms: allPlatforms },
  { name: 'PullToRefreshBoxScreen', platforms: androidOnly },
  { name: 'RadioButtonScreen', platforms: androidOnly },
  { name: 'Rotation3DEffectScreen', platforms: iosOnly },
  { name: 'RTLScreen', platforms: iosOnly },
  { name: 'ScrollViewScreen', platforms: iosOnly },
  { name: 'ScrollViewSharedPositionScreen', platforms: iosOnly },
  { name: 'SectionScreen', platforms: iosOnly },
  { name: 'SegmentedControlScreen', platforms: androidOnly },
  { name: 'ShapeScreen', platforms: androidOnly },
  { name: 'ShapesScreen', platforms: iosOnly },
  { name: 'ShareLinkScreen', platforms: iosOnly, excludedOnTV: true },
  { name: 'SliderScreen', platforms: allPlatforms, excludedOnTV: true },
  { name: 'StepperScreen', platforms: iosOnly, excludedOnTV: true },
  { name: 'SurfaceScreen', platforms: androidOnly },
  { name: 'SwitchScreen', platforms: androidOnly },
  { name: 'SyncSwitchScreen', platforms: androidOnly },
  { name: 'TabViewScreen', platforms: iosOnly },
  { name: 'TextFieldScreen', platforms: allPlatforms, excludedOnTV: true },
  { name: 'TextScreen', platforms: allPlatforms },
  { name: 'ToggleButtonScreen', platforms: androidOnly },
  { name: 'ToggleScreen', platforms: iosOnly },
  { name: 'TooltipScreen', platforms: androidOnly },
];
